#!/usr/bin/env bash
set -euo pipefail

# Fetch recently merged PRs that were generated by craft-pr (contain craft-pr-checksum),
# along with their full edit history from GitHub's GraphQL userContentEdits API.
# Returns structured JSON to stdout, errors to stderr.
#
# Usage: feedback.sh [--config config.yml] [--since "30 days ago"] [--author your-username]
#                    [--limit 20] [--exclude "150,148"]
#
# Config file support:
#   Reads github.org, github.repo, and github.username from a YAML config file.
#   CLI flags always override config values. See examples/config.yml for the template.

SINCE="30 days ago"
AUTHOR=""
LIMIT=20
EXCLUDE=""
REPO_OWNER=""
REPO_NAME=""
CONFIG_FILE=""

# Load a value from a YAML config file.
# Falls back to the provided default if the key is missing or PyYAML isn't available.
# Usage: load_config_value <file> <dotted.key> [default]
load_config_value() {
  local file="$1" key="$2" default="${3:-}"
  python3 -c "
import sys
try:
    import yaml
except ImportError:
    print('WARN: PyYAML not installed. Config file support requires: pip3 install pyyaml', file=sys.stderr)
    sys.exit(1)
try:
    with open(sys.argv[1]) as f:
        data = yaml.safe_load(f)
    keys = sys.argv[2].split('.')
    val = data
    for k in keys:
        val = val[k]
    print(val)
except (KeyError, TypeError, FileNotFoundError):
    sys.exit(1)
" "$file" "$key" 2>/dev/null || echo "$default"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) CONFIG_FILE="$2"; shift 2 ;;
    --since) SINCE="$2"; shift 2 ;;
    --author) AUTHOR="$2"; shift 2 ;;
    --limit) LIMIT="$2"; shift 2 ;;
    --exclude) EXCLUDE="$2"; shift 2 ;;
    --help)
      cat >&2 <<'USAGE'
Usage: feedback.sh [--config config.yml] [--since "30 days ago"] [--author your-username]
                   [--limit 20] [--exclude "150,148"]

Fetches merged PRs with craft-pr-checksum and their edit histories.

Options:
  --config FILE    YAML config file for org-specific defaults (see examples/config.yml).
  --since PERIOD   How far back to search (default: "30 days ago").
  --author USER    GitHub username. Overrides config github.username.
  --limit N        Max PRs to return (default: 20).
  --exclude NUM    Comma-separated PR numbers to skip (already processed).

Config keys read (CLI flags override):
  github.org       -> repository owner
  github.repo      -> repository name
  github.username  -> PR author to search for
USAGE
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Apply config values where CLI flags weren't provided
if [[ -n "$CONFIG_FILE" ]]; then
  [[ -z "$REPO_OWNER" ]] && REPO_OWNER=$(load_config_value "$CONFIG_FILE" "github.org" "")
  [[ -z "$REPO_NAME" ]]  && REPO_NAME=$(load_config_value "$CONFIG_FILE" "github.repo" "")
  [[ -z "$AUTHOR" ]]     && AUTHOR=$(load_config_value "$CONFIG_FILE" "github.username" "")
fi

# Fall back to placeholders if still empty
: "${REPO_OWNER:=your-org}"
: "${REPO_NAME:=your-app}"
: "${AUTHOR:=your-username}"

SINCE_DATE=$(python3 -c "
from datetime import datetime, timedelta
import re, sys
s = sys.argv[1].lower().strip()
m = re.match(r'(\d+)\s*(day|week|month)s?\s*ago', s)
if m:
    n, unit = int(m.group(1)), m.group(2)
    if unit == 'day': delta = timedelta(days=n)
    elif unit == 'week': delta = timedelta(weeks=n)
    elif unit == 'month': delta = timedelta(days=n*30)
    else: delta = timedelta(days=30)
    print((datetime.now() - delta).strftime('%Y-%m-%d'))
else:
    print((datetime.now() - timedelta(days=30)).strftime('%Y-%m-%d'))
" "$SINCE" 2>/dev/null || date -v-30d +%Y-%m-%d 2>/dev/null || date -d "30 days ago" +%Y-%m-%d)

echo "Searching for merged PRs since ${SINCE_DATE} (owner: ${REPO_OWNER}, repo: ${REPO_NAME}, author: ${AUTHOR})..." >&2

EXCLUDE_ARRAY="[]"
if [[ -n "$EXCLUDE" ]]; then
  EXCLUDE_ARRAY=$(echo "$EXCLUDE" | tr ',' '\n' | jq -R 'tonumber' | jq -s '.')
fi

MERGED_PRS=$(gh pr list \
  --state merged \
  --author "$AUTHOR" \
  --search "merged:>=${SINCE_DATE}" \
  --limit "$LIMIT" \
  --json number,title,mergedAt,body 2>/dev/null || echo "[]")

CANDIDATES=$(echo "$MERGED_PRS" | jq --argjson exclude "$EXCLUDE_ARRAY" '
  [.[] |
    select(.body | contains("craft-pr-checksum:")) |
    select(.number as $n | $exclude | index($n) | not)
  ]
')

CANDIDATE_COUNT=$(echo "$CANDIDATES" | jq 'length')

if [[ "$CANDIDATE_COUNT" -eq 0 ]]; then
  jq -n \
    --arg since "$SINCE_DATE" \
    --arg author "$AUTHOR" \
    '{
      success: true,
      since: $since,
      author: $author,
      prs: [],
      count: 0
    }'
  exit 0
fi

echo "Found ${CANDIDATE_COUNT} craft-pr-generated PRs. Fetching edit histories..." >&2

RESULTS="[]"

while IFS= read -r pr_number; do
  [[ -z "$pr_number" ]] && continue

  echo "  Fetching edits for PR #${pr_number}..." >&2

  EDITS_JSON=$(gh api graphql -f query="
    {
      repository(owner: \"${REPO_OWNER}\", name: \"${REPO_NAME}\") {
        pullRequest(number: ${pr_number}) {
          userContentEdits(first: 50) {
            nodes {
              editedAt
              diff
              editor { login }
            }
          }
        }
      }
    }
  " 2>/dev/null || echo '{"data":{"repository":{"pullRequest":{"userContentEdits":{"nodes":[]}}}}}')

  EDITS=$(echo "$EDITS_JSON" | jq '
    [.data.repository.pullRequest.userContentEdits.nodes[] |
      {
        edited_at: .editedAt,
        editor: .editor.login,
        body: .diff
      }
    ] | sort_by(.edited_at)
  ')

  PR_DATA=$(echo "$CANDIDATES" | jq --argjson num "$pr_number" --argjson edits "$EDITS" '
    [.[] | select(.number == $num)][0] |
    {
      number: .number,
      title: .title,
      merged_at: .mergedAt,
      final_body: .body,
      edits: $edits
    }
  ')

  RESULTS=$(echo "$RESULTS" | jq --argjson pr "$PR_DATA" '. + [$pr]')

done <<< "$(echo "$CANDIDATES" | jq -r '.[].number')"

FINAL_COUNT=$(echo "$RESULTS" | jq 'length')

jq -n \
  --arg since "$SINCE_DATE" \
  --arg author "$AUTHOR" \
  --argjson prs "$RESULTS" \
  --argjson count "$FINAL_COUNT" \
  '{
    success: true,
    since: $since,
    author: $author,
    prs: $prs,
    count: $count
  }'
